name = "QSymbolic"
uuid = "51350ce6-7c10-437b-ae15-8948c6144b7d"
authors = ["Author Name <email@example.com>"]
version = "0.1.0"

[deps]
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[compat]
TestItemRunner = "1.1.4"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
