name = "QSymbolic"
uuid = "51350ce6-7c10-437b-ae15-8948c6144b7d"
authors = ["Li-Xun Cai <cailixun23@gmail.com>"]
version = "0.3.0"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[compat]
Reexport = "1"
Symbolics = "7"
TestItemRunner = "1.1.4"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
